#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli')
    echo 'Warning: Consolle should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL;

define('__APP_BASE_PATH__', __DIR__);

require __DIR__ . '/bootstrap/autoload.php';

error_reporting(-1);

if (function_exists('ini_set'))
{
    @ini_set('display_errors', 1);

    $memoryInBytes = function ($value)
    {
        $unit = strtolower(substr($value, -1, 1));
        $value = (int) $value;
        switch($unit) {
            case 'g':
                $value *= 1024;
            // no break (cumulative multiplier)
            case 'm':
                $value *= 1024;
            // no break (cumulative multiplier)
            case 'k':
                $value *= 1024;
        }

        return $value;
    };

    $memoryLimit = trim(ini_get('memory_limit'));
    // Increase memory_limit if it is lower than 1GB
    if ($memoryLimit != -1 && $memoryInBytes($memoryLimit) < 1024 * 1024 * 1024) {
        @ini_set('memory_limit', '1G');
    }
    unset($memoryInBytes, $memoryLimit);
}

$app = require_once __DIR__ . '/bootstrap/app.php';

// Run the command application
$kernel = $app->make('Consolle\Contracts\Kernel');
$kernel->run();
